### ISSUE TITLE
Rename node-xmpp

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/node-xmpp#206]
node-xmpp runs in the browser, more transport might be added (Chrome socket API, Web API socket API, WebRTC, ...) while reorganizing the project, maybe it's worth thinking of it?

**Comment by sonnyp** [comment]
Hey I'm reopening this just to check other contributors opinion.
@dodo you made a good point but still, I think the name is misleading people into thinking this is node only. Also support for io.js kinda make a point too.

**Comment by sonnyp** [comment]
what about esmpp?

**Comment by smokku** [comment]
https://www.npmjs.com/package/xmpp.js is free

**Comment by sonnyp** [comment]
@smokku IIRC npm forbids `.` in package name.
Also the availability on the repository is not an issue as we know use the `@xmpp` scope.

**Comment by sonnyp** [comment]
(In any case I like the name xmpp.js, simple, concise, explicit)

**Comment by astro** [comment]
I like the **xmpp.js** moniker.

**Comment by sonnyp** [comment]
@astro @smokku if we do rename the project `xmpp.js` do you think we should publish the `xmpp.js` package as well? if so how would it differ from our `@xmpp` scoped packages?

**Comment by smokku** [comment]
I think we should. To assign the name at least.

`xmpp.js` package could do nothing - just pull other packages as dependencies.

**Comment by smokku** [comment]
https://npms.io/search?q=xmpp does not give any hints that one would want `@xmpp/client`. `xmpp.js` with a good description should be clearly visible there.

**Comment by sonnyp** [comment]
I propose we wait for the rewrite to be stable then release a 1.0 and rename it xmpp.js

**Comment by sonnyp** [comment]
Out of clarity 1.0 will not include BOSH or node-xmpp-server (unless someone is willing to work on this) but I'll work on that later on.

**Comment by afinnell** [comment]
Necro'ing the thread but for a worthy cause. 

XMPP is STILL being used today for corporate communications at rather large companies. The why's and buts of it all aren't important. What is important is having TLS support along with Both Client and Server Certification validation. If TLS is implemented then all that should come free I would think. But without TLS then I can't see XMPP being used for anything. While if it did, this project and others would have a much larger user base and adoption rate.

And for what it's worth, if this is meant for the Browser, I agree with the name change. Only 1% of all developers understand the nitty gritty details of what it is to use the Node platform for devops, vs. using it to run production services vs. Node not being exclusively tied to Chromes V8. Not to mention, that if one uses web pack they are using nodes package management at some level. 

My point being, that Semantics matter and something being Browser only versus Node Runtime only is huge. Just my two cents.

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp/pull/429

a few more fixes, documentation and we'll be ready to hit xmpp.js 1.0.0

**Comment by sonnyp** [comment]
closing in favor of https://github.com/node-xmpp/node-xmpp/issues/434
