### ISSUE TITLE
Browserify error "window is not defined"

### ISSUE THREAD

**Issue by twhtanghk** [node-xmpp/node-xmpp#209]
browerify the following index.js always reports 
<pre>
window.XMPP = exports
^
ReferenceError: window is not defined
</pre>
Any idea or suggestion. Thanks

index.js:
<pre>
(function() {
  var xmpp;

  xmpp = require('node-xmpp');

  xmpp.on('online', function() {
    return console.log('online');
  });

  xmpp.connect({
    jid: 'abc.com',
    password: '',
    boshURL: 'http://abc.com:5280/http-bind'
  });

}).call(this);
</pre>

**Comment by sonnyp** [comment]
No response, closing
