### ISSUE TITLE
Disconnected from server

### ISSUE THREAD

**Issue by SatisfactionSania** [node-xmpp/node-xmpp#239]
I can't connect to my server by sample:https://github.com/node-xmpp/node-xmpp/blob/master/examples/c2s.js
Server send:<stream:error><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-streams"/><text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml:lang="en">syntax error</text></stream:error>
and he listen my stanzas twice:
AUTH user@site.com -> pass
AUTH user@site.com -> pass
DISCONNECT
DISCONNECT
i've installed: node.js@0.10.26, node-xmpp@0.15.0

**Comment by sonnyp** [comment]
@SatisfactionSania yes this should be fixed with newer version, can you try?

**Comment by sonnyp** [comment]
No response, closing
