### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/node-xmpp#264]
This isn't related to node-xmpp only but all node-xmpp modules.

Code style seem to diverge a lot between modules and even files.

I propose we switch to [ESLint](http://eslint.org/) which offers more appearance options than jshint and add [EditorConfig](http://editorconfig.org/) with strict rules for each repository.

**Comment by chris-rock** [comment]
I like the idea to have strict rules. Any specific why we should not continue with JSHint? I just want to understand the decision process

**Comment by sonnyp** [comment]
@chris-rock eslint has plugins and offer stricter rules

http://eslint.org/docs/about/ for more information

**Comment by chris-rock** [comment]
just saw it. pretty cool, to have it customizable

**Comment by lloydwatkin** [comment]
Yes some of the code has been cleaned up (where touched) but there is still lots in random styles. If eslint can give us what we need then I am happy to accept a pull request switching us to that setup :)

**Comment by sonnyp** [comment]
What do you guys think about https://github.com/feross/standard ?

**Comment by lloydwatkin** [comment]
Nothing against it, but we do have a fairly decent coding style setup already. Does it gain us anything?
