### ISSUE TITLE
Could you provide some sample code to subscribe to a node? 

### ISSUE THREAD

**Issue by LeeSingFanda** [node-xmpp/node-xmpp#265]
I'm writing some code to receive to some nodes in an XMPP server. Node names are known but I can't any function to do the subscription. There is too little documentation available. 

Sample subscription IQ: 
&lt;iq type='set'  from='francisco@denmark.lit/barracks'  to='pubsub.shakespeare.lit' id='sub1'>
  &lt;pubsub xmlns='http://jabber.org/protocol/pubsub'>
    &lt;subscribe  node='princely_musings'   jid='francisco@denmark.lit'/>
  &lt;/pubsub>
&lt;/iq>

I tried client.send(subscription_message), I receive error on 

&lt;error code="404" type="cancel">&lt;remote-server-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>&lt;/error>

I confirmed that I can telnet to the server and on the specific port. When I checked the server log, I found error message like: 

 org.jivesoftware.openfire.http.HttpBindServlet - Client provided invalid session: 29d728ad. [192.168.xx.xx]

**Comment by lloydwatkin** [comment]
Hi @LeeSingFanda, 

I believe I've replied to your post on stackoverflow, let me know if that doesn't help.

Please can you also use [node-xmpp-client](https://github.com/node-xmpp/node-xmpp-client) rather than node-xmpp (as it'll be more up to date).

Cheers, Lloyd.
