### ISSUE TITLE
Update browserify

### ISSUE THREAD

**Issue by wesleytodd** [node-xmpp/node-xmpp#266]
There is an issue deep in the bowels of some dependencies that cause git issues.  Updating browserify, which is like 6 major versions behind, will fix it.  If you want I can submit a PR, but this seems like an easy one for you all to just knock out.  Thanks!

**Comment by lloydwatkin** [comment]
Hmm thanks @wesleytodd, actually travis should publish an updated version with each commit to master, I'll take a look at what that isn't happening but will manually push now.

**Comment by lloydwatkin** [comment]
Actually I've just noticed this is the `node-xmpp` project not `node-xmpp-client` if you pick up the browserified version from there it'll be up to date.

**Comment by wesleytodd** [comment]
This is on our server.  Is there a `node-xmpp-server` package we should be using instead of this?

**Comment by wesleytodd** [comment]
And FWIW, this is still including a version of browserify that is OLD.

This package includes: `~3.19.1`
Current browserify version: `9.0.3`

**Comment by lloydwatkin** [comment]
@wesleytodd yes its better to use the broken down `node-xmpp-*` projects. Will look at upgrading browserify thanks for letting us know.
