### ISSUE TITLE
Emit event when sending/receiving - feature request

### ISSUE THREAD

**Issue by RobertLarsen** [node-xmpp/node-xmpp#268]
I need statistics on the amount of data that is sent/received. The received data can be retrieved by listening for 'data' events, but for the sent data I need to both call rmXmlns on the connection and serialize the stanza (which the connection does also).

Could be nice, if an event was emitted when raw data was ready to be sent.

**Comment by lloydwatkin** [comment]
For which project are you attempting to do this @RobertLarsen ? `node-xmpp` is now split into several projects (`-client`, `-component`, `-server`, and `-core`). I'd imagine any change we'd need to make to enable this would be on `node-xmpp-core` so once we have a response we can move this issue as appropriate.

**Comment by RobertLarsen** [comment]
That was fast.
I'm building a component, but don't you think this could be relevant to all types?

**Comment by RobertLarsen** [comment]
Is this doable?
Do you need more information from me?

**Comment by lloydwatkin** [comment]
@RobertLarsen yeah it is doable, but I think all the core contriutors are busy with projects at the moment so don't have time. I'd be happy to accept a pull request (with tests) if you have the time. Cheers, Lloyd.
