### ISSUE TITLE
XMPP pubsub example code

### ISSUE THREAD

**Issue by flyingmouse** [node-xmpp/node-xmpp#269]
Hello I am trying to do Publish/Subscribe using node-xmpp, but I find it a little difficult and there is  not much documentation after googling. Could someone give me a hand plz? Thanks in advance.

**Comment by lloydwatkin** [comment]
You could try [https://github.com/xmpp-ftw/xmpp-ftw-pubsub](xmpp-ftw-pubsub). That implements a large part of the pubsub spec and you'll be able to gather the build stanzas from that (if you don't want to use directly).
