### ISSUE TITLE
Install fails on Windows machine

### ISSUE THREAD

**Issue by liviuignat** [node-xmpp/node-xmpp#270]
Hi, 

I am trying to install node-xmpp on a Windows 7 PC and it fails. As always on Windows, it seems to fail to build dependencies with node-gyp. Running node version is 0.12.

The dependencies that fail are from node-xmpp-core: node-stringprep and ltx.

Is it possible to fix this please?

Thanks.

**Comment by lloydwatkin** [comment]
Which part of node-xmpp are you trying to use?

* node-xmpp-client
* node-xmpp-component
* node-xmpp-server
?

Could you try installing the appropriate part (and checking issues in that project) and then get back to us (in a new issue under the appropriate project) if you are unable to continue. Thanks!

**Comment by liviuignat** [comment]
The above 3'd party dependencies, which cannot be installed, are in node-xmpp-core, which is a dependency in all of the above projects.

**Comment by lloydwatkin** [comment]
That is correct, but I've added a related note under your new issue - https://github.com/node-xmpp/node-xmpp-core/issues/67
