### ISSUE TITLE
library question...connecting to ejabberd

### ISSUE THREAD

**Issue by pateljatin** [node-xmpp/node-xmpp#271]
Hello,

I want mobile app clients connect to node app server and also to the ejabberd server.  However, overtime users are chatting or sending messages to ejabberd server, how would node app server using node-xmpp listen on the conversations.  Is that the component connection? Which node-xmpp example would I use in this scenario?

Also 2nd approach:
- Connect mobile apps to node app server using http?  and then node-app-server connects to ejabberd. meaning all communication from mobile chat apps only goes to node app server and then node app server sends them over to ejabberd. Does this make sense? Which node-xmpp example would I use in this scenario?

Thanks!

**Comment by lloydwatkin** [comment]
Scenario 2: You could use something like xmpp-ftw for this.
Scenario 1: It depends very much on how ejabberd works and whether it would allow you to do this. You'd need to contact the developers for help.
