### ISSUE TITLE
Cannot load StringPrep-0.7.0 bindings (using fallback). You may need to `npm install node-stringprep`

### ISSUE THREAD

**Issue by PraveenVignesh** [node-xmpp/node-xmpp#273]
Hi,

When i tried examples, it throws the error,

Cannot load StringPrep-0.7.0 bindings (using fallback). You may need to `npm install node-stringprep`

I tried npm install node-stringprep, but it still throwing same error.

**Comment by lloydwatkin** [comment]
Do you have `libicu-dev` installed as per the [instructions](http://node-xmpp.org/doc/stringprep.html)

**Comment by PraveenVignesh** [comment]
Thanks, now working fine.
