### ISSUE TITLE
This module is abandonware.

### ISSUE THREAD

**Issue by iliakan** [node-xmpp/node-xmpp#274]
The latest security release iojs is a "must" upgrade. 

But node-xmpp is not compatible.

Leaving the issue as a note here, so that others can see it and not use it.

**Comment by sonnyp** [comment]
You already raised the issue, why don't you give some help?

https://github.com/node-xmpp/node-xmpp/issues/272

**Comment by iliakan** [comment]
Because you don't even try to install it.
If you will not see the error then I will provide the details.

**Comment by sonnyp** [comment]
Yes that would be useful, see https://github.com/node-xmpp/node-xmpp/issues/272#issuecomment-114788622

Let's move the discussion back to https://github.com/node-xmpp/node-xmpp/issues/272
