### ISSUE TITLE
express js wirh node-xmpp connection

### ISSUE THREAD

**Issue by pokal4u** [node-xmpp/node-xmpp#276]
Hi,

I am new to node js, 
I try to implement node-xmpp module with express js, but i did't get any response at console from xmpp

my appp.js code:

```javascript
var express = require('express');
var stormpath = require('express-stormpath');
var xmpp = require('node-xmpp');
var app = express();

app.set('views', './views');
app.set('view engine', 'jade');

app.get('/', function(req, res) {
  res.render('home', {
    title: 'Welcome'
  });
});
app.use('/profile', function(req, res) {
  res.render('profile', {
    title: 'Welcome'
  });
});
var client = new xmpp.Client({jid: 'abc@domain.com', password: 'password'});
client.on('online', function(data) {
    console.log('Connected as ' + data.jid.user + '@' + data.jid.domain + '/' + data.jid.resource);    
});
client.on('stanza', function(stanza) {
    console.log('RECEIVED STANZA', stanza);
});
client.on('offline', function () {
    console.log('Client is offline');
});
client.on('connect', function () {
    console.log('Client is connected');
});
client.connect();
app.listen(8088);
```
Only express js working fine like:  http://www.domain.com:8080,  http://www.domain.com:8080/profile

problem with node-xmpp.

Please check whats wrong with my code.

And what are the JID and password? where can I create from?

Thanks
Pokal

**Comment by sonnyp** [comment]
express is HTTP and node-xmpp is XMPP
those are 2 different and incompatible protocols

I'm not sure to understand what you are trying to do

**Comment by pokal4u** [comment]
Ok thank you

I trying to imeplement chat module using node-xmpp

Can you help me?

**Comment by sonnyp** [comment]
@pokal4u this is a lot of work specially if you are new to Node.js I'd recommend to start with an existing XMPP server.

Have a look at https://github.com/node-xmpp/radiowave if you're looking for a Node.js solution.

**Comment by pokal4u** [comment]
OK, but i need to implement this module

forgot express js, can you please tell me  how to run the below code? 

var xmpp = require('node-xmpp');
var client = new xmpp.Client({jid: 'abc@domain.com', password: 'password'});
client.on('online', function(data) {
    console.log('Connected as ' + data.jid.user + '@' + data.jid.domain + '/' + data.jid.resource);    
});
client.on('stanza', function(stanza) {
    console.log('RECEIVED STANZA', stanza);
});
client.on('offline', function () {
    console.log('Client is offline');
});
client.on('connect', function () {
    console.log('Client is connected');
});
client.connect();

**Comment by pokal4u** [comment]
HI,
With the same code i given sample jid and passwords are romeo and romeo

Then i got response:

Client is connected

TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Client.EventEmitter.emit (events.js:74:15)

what is this error?

**Comment by pokal4u** [comment]
Error: XML parse error
    at Connection.error (/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/connection.js:411:24)
    at StreamParser.<anonymous> (/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/connection.js:224:14)

**Comment by pokal4u** [comment]
Now i am getting error like:  XMPP authentication failure

**Comment by sonnyp** [comment]
You cannot use a client on its own, you need an XMPP server as well.

**Comment by pokal4u** [comment]
any documentation links?

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp-server
https://github.com/node-xmpp/radiowave

**Comment by pokal4u** [comment]
HI,

I got error like:


<stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" version="1.0" id="315356f1469c2bf5df67f05f6dbe92db"><stream:error><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-streams"/><text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml:lang="en">syntax error</text></stream:error></stream:stream>

code:

var xmpp = require('node-xmpp');
var c2s = new xmpp.C2SServer({
    port: 8088,
    domain: 'localhost'

});

// On Connect event. When a client connects.
c2s.on("connect", function(client) {
    c2s.on("register", function(opts, cb) {
        console.log("REGISTER");
    cb(true);
    });

    client.on("authenticate", function(opts, cb) {
        console.log("AUTH" + opts.jid + " -> " +opts.password); 
    cb(null, opts); 
    });

    client.on("online", function() {
        console.log("ONLINE");
        client.send(new xmpp.Message({ type: 'chat' }).c('body').t("Hello there, little client."));
    });

    client.on("stanza", function(stanza) {
        console.log("STANZA" + stanza);

    });

    client.on("disconnect", function(client) {
        console.log("DISCONNECT");
    });

});

In console I got DISCONNECT messages only.


please help me..

**Comment by pokal4u** [comment]
console.log(client) response


{ authenticated: false,
  server:
   { options: { port: 8088, domain: 'localhost' },
     availableSaslMechanisms: [ [Object] ],
     c2sPort:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _connections: 4,
        connections: [Getter/Setter],
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        allowHalfOpen: false,
        _connectionKey: '6::::8088' },
     _events: { connect: [Function], shutdown: [Object], register: [Object] } },
  generateId:
   { [Function]
     hats: { '8a36a7457aa015984b04bb223ae15fe9': undefined },
     get: [Function],
     set: [Function],
     bits: 128,
     base: 16 },
  connection:
   { domain: null,
     _events:
      { connection: [Function],
        end: [Object],
        reconnect: [Object],
        stanza: [Function],
        drain: [Function],
        data: [Function],
        close: [Function],
        error: [Function],
        connect: [Object],
        disconnect: [Object],
        streamStart: [Function] },
     _maxListeners: 10,
     streamAttrs: { version: '1.0', id: '8a36a7457aa015984b04bb223ae15fe9' },
     xmlns:
      { stream: 'http://etherx.jabber.org/streams',
        '': 'jabber:client' },
     rejectUnauthorized: false,
     serialized: false,
     requestCert: false,
     servername: undefined,
     connected: false,
     reconnect: false,
     listen: [Function],
     connect: [Function],
     disconnect: [Function],
     end: [Function],
     socket:
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        onend: null,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        pipe: [Function],
        addListener: [Function],
        on: [Function],
        pause: [Function],
        resume: [Function],
        read: [Function],
        _consuming: true,
        serializeStanza: [Function] },
     parser:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        parser: [Object],
        bytesParsed: 0,
        maxStanzaSize: undefined,
        bytesParsedOnStanzaBegin: 0 },
     _connection:
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        onend: null,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        pipe: [Function],
        addListener: [Function],
        on: [Function],
        pause: [Function],
        resume: [Function],
        read: [Function],
        _consuming: true,
        serializeStanza: [Function] } },
  _events: { close: [Function], error: [Function] } }
{ authenticated: false,
  server:
   { options: { port: 8088, domain: 'localhost' },
     availableSaslMechanisms: [ [Object] ],
     c2sPort:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        _connections: 5,
        connections: [Getter/Setter],
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        allowHalfOpen: false,
        _connectionKey: '6::::8088' },
     _events: { connect: [Function], shutdown: [Object], register: [Object] } },
  generateId:
   { [Function]
     hats: { e78f6f50de8c4014f6747e54a237fca7: undefined },
     get: [Function],
     set: [Function],
     bits: 128,
     base: 16 },
  connection:
   { domain: null,
     _events:
      { connection: [Function],
        end: [Object],
        reconnect: [Object],
        stanza: [Function],
        drain: [Function],
        data: [Function],
        close: [Function],
        error: [Function],
        connect: [Object],
        disconnect: [Object],
        streamStart: [Function] },
     _maxListeners: 10,
     streamAttrs: { version: '1.0', id: 'e78f6f50de8c4014f6747e54a237fca7' },
     xmlns:
      { stream: 'http://etherx.jabber.org/streams',
        '': 'jabber:client' },
     rejectUnauthorized: false,
     serialized: false,
     requestCert: false,
     servername: undefined,
     connected: false,
     reconnect: false,
     listen: [Function],
     connect: [Function],
     disconnect: [Function],
     end: [Function],
     socket:
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        onend: null,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        pipe: [Function],
        addListener: [Function],
        on: [Function],
        pause: [Function],
        resume: [Function],
        read: [Function],
        _consuming: true,
        serializeStanza: [Function] },
     parser:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        parser: [Object],
        bytesParsed: 0,
        maxStanzaSize: undefined,
        bytesParsedOnStanzaBegin: 0 },
     _connection:
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 10,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        onend: null,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        pipe: [Function],
        addListener: [Function],
        on: [Function],
        pause: [Function],
        resume: [Function],
        read: [Function],
        _consuming: true,
        serializeStanza: [Function] } },
  _events: { close: [Function], error: [Function] } }

**Comment by sonnyp** [comment]
what options do you pass to Client ?

**Comment by pokal4u** [comment]
var xmpp = require('node-xmpp');
var c2s = new xmpp.C2SServer({
port: 8088,
domain: 'localhost'
});

// On Connect event. When a client connects.
c2s.on("connect", function(client) {

});

**Comment by sonnyp** [comment]
to client, not to server

**Comment by pokal4u** [comment]
HI,
I need to implement chat appllication on node xmpp server.
Please tell me process like
1.  make directory
2. install modules
3. anything else..


Please..

**Comment by pokal4u** [comment]
I given my code above...

**Comment by sonnyp** [comment]
you didn't send your new XMPP.Client code

**Comment by pokal4u** [comment]
I didn't understand..

Please send some example client code  and where it place to call

**Comment by sonnyp** [comment]
how do you create the XMPP client?

**Comment by sonnyp** [comment]
you need to specify the host and the port to match the server: 
```javascript
var client = new xmpp.Client({jid: 'foo@localhost', password: 'password', host: 'localhost', port: 8088});```

**Comment by pokal4u** [comment]
var client = new xmpp.Client({jid: 'admin@localhost', password: 'password', host: 'localhost', port: 8088});

I created above jid,password in ejabbered account.

**Comment by pokal4u** [comment]
HI,

Now I am sending messages from admin@localhost to test@localhost

I saw those messages in ejabbered admin

![xmpp](https://cloud.githubusercontent.com/assets/498771/8643759/9b308ddc-2955-11e5-9833-c47c430fdec4.png)

How to receive those messages?

Thanks
Pokal

**Comment by lloydwatkin** [comment]
Duplicate of https://github.com/node-xmpp/node-xmpp/issues/279
