### ISSUE TITLE
Google talk xmpp JID to email

### ISSUE THREAD

**Issue by amirmamaghani** [node-xmpp/node-xmpp#277]
Is there any way to get gmail email address from JID? thx

**Comment by sonnyp** [comment]
Google XMPP JID is the same as email address

```
var jid = new JID('foo@gmail.com')
```

**Comment by amirmamaghani** [comment]
In your login credentials it is, but in stanza I got only someKindOfHash@public.talk.google.com

**Comment by sonnyp** [comment]
@amirmamaghani oh, I see what you mean no idea sorry

I think it is a feature to hide emails so I'd say no but it's worth looking for, let us know if you find out.

**Comment by amirmamaghani** [comment]
til now I find out that this is because of google's privacy settings but there has to be some way to 
http://julipedia.meroh.net/2012/07/getting-rid-of-publictalkgooglecom.html
