### ISSUE TITLE
Google talk reconnects after 20 seconds

### ISSUE THREAD

**Issue by amirmamaghani** [node-xmpp/node-xmpp#278]
I'm using this configuration for xmpp.Client
```JSON
{
                "jid": "username@gmail.com",
                "password": "pass",
                "host": "talk.google.com",
                "port": 5222,
                "preferred": "PLAIN",
                "reconnect": true
            }
```
and it reconnects each 20s. Am I doing something wrong?

**Comment by sonnyp** [comment]
you probably need to reply XMPP pings

can you check logs and see if you receive those XMPP pings? http://xmpp.org/extensions/xep-0199.html

**Comment by sonnyp** [comment]
also please use node-xmpp-client and ask client related question there https://github.com/node-xmpp/node-xmpp-client
