### ISSUE TITLE
Client Documentation: Sending messages?

### ISSUE THREAD

**Issue by sbrl** [node-xmpp/node-xmpp#280]
How do you send a message to a JID? The documentation doesn't seem to cover this and is rather incomplete.

A reference telling me how the client works would be really nice. An example if a really good documentation would be the [WebSocketClient](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md) from [websocket-node](https://github.com/theturtle32/WebSocket-Node/).

**Comment by lloydwatkin** [comment]
Assuming you are talking about `node-xmpp-client` then please take a look at the examples here: https://github.com/node-xmpp/node-xmpp-client/tree/master/examples

**Comment by sbrl** [comment]
@lloydwatkin The examples don't make sense to me, sorry.
