### ISSUE TITLE
Website is not accessible. 

### ISSUE THREAD

**Issue by c4milo** [node-xmpp/node-xmpp#283]
https://cloudup.com/cMZMM32ZP2D

**Comment by sonnyp** [comment]
sorry about that will fix this weekend.

duplicate of duplicate https://github.com/node-xmpp/node-xmpp.github.io/issues/11

**Comment by sonnyp** [comment]
fixed, sorry for the delay

**Comment by c4milo** [comment]
no problem, thank you!
