### ISSUE TITLE
How to send a message to the client from server directly?

### ISSUE THREAD

**Issue by houyewei** [node-xmpp/node-xmpp#289]
Hey guys. I want to use this library to make a instant message app which user from on client could send message to other client through the server router the message. I didn't find how to send a message from the server directly without the callback of stanza. How to do that? Thanks.

**Comment by sonnyp** [comment]
I don't understand what you mean by `without the callback of stanza`.

If it helps there are client examples here https://github.com/node-xmpp/node-xmpp-client/tree/master/examples

**Comment by houyewei** [comment]
Thanks  foryour reply.  I  means if  server  get  a  message  from  one  client,  how  to  send  the message  to  the  target  client(another  client which  rece ive  the message) . 

Sent from Outlook Mobile




On Thu, Mar 3, 2016 at 5:47 AM -0800, "Sonny Piers" <notifications@github.com> wrote:












I don't understand what you mean by without the callback of stanza.



If it helps there are client examples here https://github.com/node-xmpp/node-xmpp-client/tree/master/examples

**Comment by sonnyp** [comment]
If a message is addressed to a client, the server should forward that message to the client.

For example if you send this message from a client A to B
`
<message to="B@domain/web" type="chat">
  <body>hello</body>
</message>
`

`
var message = new Stanza('message', {to: 'B@domain/web', type: 'chat'}
message.c('body').t('hello')
client.send(message)
`

the server will forward that message to the resource (client) `web` of the user `B`.


http://xmpp.org/

**Comment by houyewei** [comment]
Here is my scripts 
**server**
```javascript
var xmpp = require('node-xmpp-server')
var server = null
var startServer = function (done) {
  // Sets up the server.
  server = new xmpp.C2S.BOSHServer({
    port: 5280,
    domain: 'localhost'
  })

  // On connection event. When a client connects.
  server.on('connection', function (client) {
    // That's the way you add mods to a given server.
    // Allows the developer to register the jid against anything they want
    client.on('register', function (opts, cb) {
      console.log('REGISTER')
      cb(true)
    })

    // Allows the developer to authenticate users against anything they want.
    client.on('authenticate', function (opts, cb) {
      console.log('server:', opts.username, opts.password, 'AUTHENTICATING')
      if (opts.password === 'secret') {
        console.log('server:', opts.username, 'AUTH OK')
        cb(null, opts)
      } else {
        console.log('server:', opts.username, 'AUTH FAIL')
        cb(false)
      }
    })

    client.on('online', function () {
      console.log('server:', client.jid.local, 'ONLINE')
    })

    // Stanza handling
    client.on('stanza', function (stanza) {
      console.log('server:', client.jid.local, 'stanza', stanza.toString())
        client.send(stanza)
    })

    // On Disconnect event. When a client disconnects
    client.on('disconnect', function () {
      console.log('server:', client.jid.local, 'DISCONNECT')
    })
  })

  server.on('listening', function(){})
}

startServer();
```
**client a**
```javascript
var xmpp = require('node-xmpp-server');
var Client = require('node-xmpp-client');

function test() {
  var clienta = new Client({
    jid: 'clienta@localhost',
    password: 'secret',
    bosh: {url: 'http://localhost:5280/http-bind/'},
  })
  clienta.on('online', function () {
    console.log('clienta: online')
  })
  clienta.on('stanza', function (stanza) {
    console.log('clienta: stanza', stanza.root().toString())
  })
}
test();
```
clientb
```javascript
var xmpp = require('node-xmpp-server')
var Client = require('node-xmpp-client');
var Stanza = require('node-xmpp-core').Stanza

function test() {
  var clientb = new Client({
    jid: 'clientb@localhost',
    password: 'secret',
    bosh: {url: 'http://localhost:5280/http-bind/'},
  });
  clientb.on('online', function () {
    console.log('clientb: online')
    var message = new Stanza('message', {to: 'clienta@localhost', type: 'chat'});
    message.c('body').t('hello');
    setInterval(function() {
      clientb.send(message);
    }, 3000)
    
  })
  clientb.on('stanza', function (stanza) {
    console.log('clientb: stanza', stanza.root().toString())
  })

}
test();
```
Client b will send message to clienta every 3 seconds. However, clienta didn't print any log to the console. Did I miss something?

**Comment by sonnyp** [comment]
node-xmpp-server is a library so it doesn't implement routing out of the box, you have to do it yourself.

**Comment by lloydwatkin** [comment]
Maybe take a look at @chris-rock's radiowave? http://www.hnwatcher.com/r/2041625/Radiowave-Node-js-JavaScript-xmpp-server
