### ISSUE TITLE
xmpp avatar feature missing

### ISSUE THREAD

**Issue by IMfenil** [node-xmpp/node-xmpp#314]
Hello Guys,

Is there any update that where the Avatar feature will be available for node-xmpp framework? Is there any way that we can update vCard and avatar using node-xmpp?

**Comment by sonnyp** [comment]
In its current state node-xmpp doesn't implement any non "core" feature. We're in the process of changing that but it'll take some time.

In any case you can definitely use node-xmpp to change your avatar.

There is two XMPP standards for avatar.
https://xmpp.org/extensions/xep-0153.html
https://xmpp.org/extensions/xep-0084.html

Just send/catch the right stanzas.

**Comment by IMfenil** [comment]
Thanks @sonnyp for the quick response.
