### ISSUE TITLE
Version 6.1.0 huh?

### ISSUE THREAD

**Issue by guness** [node-xmpp/node-xmpp#316]
I am seeing node-xmpp-client has published version 6.1.0 according to [VersionEye](https://www.versioneye.com/nodejs/node-xmpp-client/6.1.0) system. I failed to find the actual version 6.1.0 if there exists any. It seems library has been moved but cannot find the reason for mismatch.

Can you please clarify?

**Comment by sonnyp** [comment]
IIRC I published it by mistake then unpublished.

There is no version 6.1.0

**Comment by guness** [comment]
Well thanks for clarification.
Just let your know: I have also been commented on the page for v6.1.0. No need to answer there too.

**Comment by sonnyp** [comment]
@guness can you please reply to your comment there to link to this issue?

**Comment by guness** [comment]
Done.
