### ISSUE TITLE
node-xmpp-client now comes with a prebuilt browser bundle

### ISSUE THREAD

**Issue by serega3000** [node-xmpp/node-xmpp#317]
"node-xmpp-client now comes with a prebuilt browser bundle"

Where is it?

**Comment by sonnyp** [comment]
```npm install node-xmpp-client```

`node_modules/node-xmpp-client/bundle.js```

**Comment by serega3000** [comment]
Thank you for quick answer, i installed it using npm, but i did not found such file
![file](https://habrastorage.org/files/709/ac4/cb6/709ac4cb668c4b979571ef732115cab6.png)

**Comment by sahalshn** [comment]
How to use this in typescript-angular
