### ISSUE TITLE
client: file bundle.js not exists

### ISSUE THREAD

**Issue by serega3000** [node-xmpp/node-xmpp#318]
I installed it using npm, but i did not found file bundle.js
![file](https://habrastorage.org/files/709/ac4/cb6/709ac4cb668c4b979571ef732115cab6.png)

**Comment by sonnyp** [comment]
oops, that's right it's browserify.js

**Comment by serega3000** [comment]
thanks!

**Comment by serega3000** [comment]
But it definitely not work if i just include it in web page like
````
<script src="/node_modules/node-xmpp-client/browserify.js"></script>
````

**Comment by sonnyp** [comment]
do you get an error? define not work

**Comment by sevnlabs** [comment]
If I just include the browserify.js I get:
Uncaught ReferenceError: require is not defined
Uncaught ReferenceError: XMPP is not defined

**Comment by sonnyp** [comment]
fixed! sorry about that

node-xmpp-client 3.0.2
