### ISSUE TITLE
Stream error , when sending multiple simultaneous messages 

### ISSUE THREAD

**Issue by siptowebrtc** [node-xmpp/node-xmpp#319]
Hi 

I am getting below error when I am sending multiple messages to the server through node-xmpp-client 

```
{ [Error]
  stanza:
   Stanza {
     name: 'stream:error',
     parent: null,
     children: [ [Object] ],
     attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' } } }
```

please note code works perfectly fine , when we send chat one by one , code only fails when I send multiple chats  simultaneously through a script ( it was a part of stress testing we had to do before putting this in production) ,

Behavior is if script is sending 10 messages 3 our lost rest 7 are lost because of this error.

Can you please give any directions to resolve this 

My code is mentioned below 

``` javascript
/Packages we need
var express = require('express');
var bodyParser = require('body-parser');
var app        = express();
var morgan     = require('morgan');
var xmpp = require('node-xmpp-client');






// configure app to use bodyParser()
// this will let us get the data from a POST
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

var port = process.env.PORT || 8060;        // set our port

// ROUTES FOR OUR API
// =============================================================================
var router = express.Router();              // get an instance of the express Router

// test route to make sure everything is working (accessed at GET http://localhost:8080/api)
router.get('/', function(req, res) {
    res.json({ message: 'hooray! welcome to our api!' });  
});

app.use('/api', router);







// This responds a POST request for the homepage
app.post('/', function (req, res) {
   console.log("Got a POST request for the homepage");
    var message = req.body.message;
    var to = req.body.to;
//XMPP Account Details Starts from Here
var client_id = "user@jab.cp.xyz.com"; //Use any XMPP Supported Account like Gmail
var client_pwd = "password";
var client_host = "jab.cp.xyz.com";  //talk.google.com for gmail
var client_port = "5222";   //5222
var status_msg = "I am Online?";   //Set it as you want

var client = new xmpp.Client({ jid: client_id,
password: client_pwd,
host: client_host,
port: client_port
});
client.on('online', function () {
  console.log('Client is online1')
  client.send('<presence/>')

    client.on('stanza', function (stanza) {
    var reply = new xmpp.Client.Stanza('message', {
      //to: stanza.attrs.from,
        to: to,
      from: stanza.attrs.to,
      type: 'chat'
    })
   console.log("Got a POST request for the homepage1");
    reply.c('body').t(message);
   // console.log("Got a POST request for the homepage2");
      client.send(reply)
      // console.log("Got a POST request for the homepage3");

res.send(message + ' ' + to);
        client.end()
    })
})

client.on('error', function (e) {
  console.error(e)
  //process.exit(1)
})


})






app.listen(port);
console.log('Magic happens on port ' + port);
```

**Comment by sonnyp** [comment]
formatted your code blocks

can you use ```console.error(e.toString)``` in your error handler to see what is the exact XMPP stream error ?

**Comment by sonnyp** [comment]
most likely your are sending too much stanza/bytes so the server is refusing

**Comment by siptowebrtc** [comment]
I think size is not an issue here as a  just sending  one word and there is loop of only 10 iterations , however it will  too fast .

Did the changes mentioned by you , getting below additional info .



Client is online1
{ [Error]
  stanza:
   Stanza {
     name: 'stream:error',
     parent: null,
     children: [ [Object] ],
     attrs: { 'xmlns:stream': 'http://etherx.jabber.org/streams' } } }
Cannot bind resource
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by sonnyp** [comment]
You are not logging error.toString()

**Comment by siptowebrtc** [comment]
Hopefully I am doing the correct this time , please check how I am logging now  and the console details wilt error are mentioned below 

client.on('error', function (e) {
  console.error(e.toString());
  //process.exit(1)
})


Client is online1
Got a POST request for the homepage1
Got a POST request for the homepage
Got the variable
Got a POST request for the homepage
Got the variable
Got a POST request for the homepage
Got the variable
Got a POST request for the homepage
Got the variable
Client is online1
Error
Cannot bind resource
Error: read ECONNRESET
Client is online1
Error
Client is online1

**Comment by sonnyp** [comment]
Can't be sure but looks like you open too many connections for the server.

What server/version are you using?

In any case I recommend opening your XMPP client first, then having your HTTP server listening. Not opening a new client every time you receive an 
HTTP request. You'll also need to queue messages in case the XMPP clients disconnect.
