### ISSUE TITLE
node-xmpp-client prebind lost session

### ISSUE THREAD

**Issue by Hosar** [node-xmpp/node-xmpp#328]
When I create a session with the prebind  options, the session is lost after a few seconds. Even if I specify the wait parameter.

Using: openfire 4.01, node v5.6.0, "node-xmpp-client": "^3.0.2",  "node-xmpp-core": "^5.0.2".

Code
let prebind = new Client({
    jid: jid,
    password: password,
    preferred: 'PLAIN',
    bosh: {
      url: boshUrl,
      wait: 120,
      prebind: function (error, sessionInfo) {
        if (error)
          deferred.reject(new Error(error));
        else{
          deferred.resolve(sessionInfo);  
        }  
      }
    }
  });

Any idea, what I'm doing wrong?

**Comment by sonnyp** [comment]
@Hosar can you use websocket instead of BOSH?

Otherwise can you try tweaking server parameters?
