### ISSUE TITLE
Sending stream:features request

### ISSUE THREAD

**Issue by eperry** [node-xmpp/node-xmpp#330]
I am looking for some help.

We use hipchat and their specification says I can authenticate with a stream:features packet, so I don't have to use a generic JID , I can have users login with their actual userid and password

but alas I am not that good node-xmpp-client and I am hoping someone can provide me a simple example on how I would implement the XML code below

In advance thanks for any help 

https://ecosystem.atlassian.net/wiki/display/HCDEV/HipChat+XMPP+Protocol+Documentation#HipChatXMPPProtocolDocumentation-RequestAuthToken

```
Requires TLS upgrade or port 5223 first, just like other auth methods.
<!-- server sends the stream:feature like: -->
<stream:features><auth xmlns="http://hipchat.com"/></stream:features>

<!-- client passes up 0 + email + 0 + password + 0 + resource, base64 encoded -->
<!-- node and ver should contain the same values provided on the initial presence -->
<auth xmlns="http://hipchat.com" node="http://hipchat.com/client/mac" ver="22">AGdhcnJldEBoaXBjaGF0LmNvbQBnYXJyZXQAdGVzdA==</auth>

<!-- server responds with success containing full jid and host namespaces -->
<success xmlns="urn:ietf:params:xml:ns:xmpp-sasl" jid="1_1@chat.hipchat.com/iphone" api_host="api.hipchat.com" chat_host="chat.hipchat.com" muc_host="conf.hipchat.com" web_host="www.hipchat.com"/>

```

**Comment by sonnyp** [comment]
In its current form it's not possible to send custom stream features with node-xmpp.

I started working on a rework that allows that https://github.com/node-xmpp/node-xmpp/pull/309 but it's not ready.

Meanwhile I recommend you to send a PR against master that adds that stream features. Shouldn't be hard check out https://github.com/node-xmpp/node-xmpp/blob/master/packages/node-xmpp-client/lib/Client.js#L332

**Comment by edperry** [comment]
Thanks, I'll have to try it a little bit later
