### ISSUE TITLE
Migration from v0.15.0

### ISSUE THREAD

**Issue by flosse** [node-xmpp/node-xmpp#339]
Hi guys,
two years ago I deployed an application that uses `v0.15.0` of `node-xmpp` and it is still running :)
Now there are some changes that needs to be done.
Do you have any experiences with updating from `v0.15.0` to `v1.x`?
Would you recommend to update at all? What are the main changes?

**Comment by sonnyp** [comment]
@flosse I don't think the API changed much. Make sure to use the right package(s) (https://github.com/node-xmpp/node-xmpp#packages).

**Comment by sonnyp** [comment]
don't hesitate to ask here if you experience any issues

**Comment by sonnyp** [comment]
@flosse if you were using component only I recommend you watch/wait for https://github.com/node-xmpp/node-xmpp/pull/338
