### ISSUE TITLE
new line

### ISSUE THREAD

**Issue by hkjang** [node-xmpp/node-xmpp#341]
hello, thanks for this sources

in this case .. 
how can i send new line in stdout string ?

ex) 
jid> conversation1
conversation2   <-- new line
conversation3   <-- new line  

jid> conversation4

`  
            var stanza = new Client.Stanza('message', {to: toJid, type: 'chat'}).c('body').t(stdout);
            client.send(stanza);
`

**Comment by sonnyp** [comment]
@hkjang sorry I don't get it if you want to send a newline just use `hello\nworld`

**Comment by lloydwatkin** [comment]
```javascript
const stdOut = 'This\nhas\nnewlines'
const stanza = new Client.Stanza('message', { to, type }).c('body').t(stdout)
client.send(stanza)


```
