### ISSUE TITLE
'xmpp/jid' is not in the npm registry

### ISSUE THREAD

**Issue by markusdanek** [node-xmpp/node-xmpp#342]
Hey,

I get the following error in our Jenkins job during npm install:

```
10:58:49 npm WARN deprecated node-xmpp-stanza@1.1.1: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
10:58:50 npm ERR! 404 Not Found
10:58:50 npm ERR! 404 
10:58:50 npm ERR! 404 'xmpp/jid' is not in the npm registry.
10:58:50 npm ERR! 404 You should bug the author to publish it
10:58:50 npm ERR! 404 It was specified as a dependency of 'node-xmpp-core'
10:58:50 npm ERR! 404 
10:58:50 npm ERR! 404 Note that you can also install from a
10:58:50 npm ERR! 404 tarball, folder, or http url, or git url.
```

Its available at NPM via _npmjs.com/package/@xmpp/jid_, but it is not available in the NPM registry as **registry.npmjs.org/@xmpp/jid** but that is the way npm wants to fetch and resolve it.

**Comment by sonnyp** [comment]
what's your npm version? you need a version greater than 2.7.0

see https://docs.npmjs.com/getting-started/scoped-packages

**Comment by markusdanek** [comment]
Thanks @sonnyp for the info!

Did not knew that and we used npm v1.4.21 because that is the only version which is in the official Debian repo.

**Comment by thepianist2** [comment]
this work for me:

`npm config set @xmpp:registry https://registry.npmjs.org/`
