### ISSUE TITLE
Client send long pause on Windows

### ISSUE THREAD

**Issue by 0x30** [node-xmpp/node-xmpp#344]
I'm having a strange issue using node-xmpp-client where there is a considerable delay (10-15s)  after sending a `<message>` stanza until the server receives it. I'm only seeing this issue when I run the client in Windows; it runs fine on Linux/OSX.
I'm also using node-xmpp-server on the backend (using TLSv1.2).
```
node v6.5.0
node-xmpp-client v3.0.2
node-xmpp-client v2.2.2
```
Any ideas would be appreciated.

**Comment by sonnyp** [comment]
I have no idea but updating node might help.

**Comment by 0x30** [comment]
This is resolved now (was caused by stream double-buffering). Thanks.

**Comment by wxplovecc** [comment]
@0x30 how to resolve ,i have met this too
