### ISSUE TITLE
How to get file transfer progress?

### ISSUE THREAD

**Issue by karanbalkar** [node-xmpp/node-xmpp#362]
Note: This a a feature request and not an issue! 

Hi All,

I am trying to send an image file from device A to device B. The file gets transferred successfully. However, I need to monitor the progress of the file transfer and send the device how much percentage of the file has been transferred.

Is this currently possible using node-xmpp?

**Comment by sonnyp** [comment]
what method do you use?

**Comment by karanbalkar** [comment]
I am not using any method as of now. I am trying to find a solution for the same. Is there a similar method available that I can try out in node-xmpp?

**Comment by sonnyp** [comment]
@karanbalkar I mean what method do you use to send the image file?

**Comment by danielmain** [comment]
I'm also very interested to know how to send files between users.
Do you implement SI File Transfer (XEP-0096) or Jingle (XEP-0166)?

**Comment by sonnyp** [comment]
@danielmain no but we now have a plugin infrastructure that would allow to do so

Let me know if you're interested in giving it a try.

**Comment by karanbalkar** [comment]
Hi Sonny,

I would like to give it a try. So do you mean to say that you now have a
plugin that gives the file transfer progress??

Regards,
Karan
