### ISSUE TITLE
Cannot install @xmpp/console

### ISSUE THREAD

**Issue by smokku** [node-xmpp/node-xmpp#364]
When I try to install `@xmpp/console` I get:
```
$ npm install -g @xmpp/console

npm ERR! Linux 4.9.8-201.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@xmpp/console"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @xmpp/console
npm ERR! 404 
npm ERR! 404  '@xmpp/console' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
[...]
```

**Comment by sonnyp** [comment]
oops; please try again should be fixed

**Comment by smokku** [comment]
Works now. Thanks.

**Comment by sonnyp** [comment]
@smokku I don't think we have any users for `@xmpp/console` yet please let me know your thoughts or missing features.

**Comment by smokku** [comment]
I'm using it while developing my jabber server (based on node-xmpp-server) to test stuff and it is extremely cool and useful. Thanks for the great code in this (node-xmpp) project. Console is great to get a grip what is on the wire. I was using Psi's XML console, but this is much better and I do not need to work around things a full client sends without asking me.

The features I miss so far:

- persistent history - after I restart my server and reconnect console I do not have the test stanzas in history anymore and need to copy paste
- continuation prompt - as soon as I press `Enter` stanza is parsed and if it is not complete I get `❌ invalid XML "<..." Error: Incomplete document`; and as transmitted stanzas are pretty-printed it is painful to copy-paste stanzas from previous session to send again (see previous point)

**Comment by smokku** [comment]
`xmpp-console` does not start session after connecting. Is it by design?

**Comment by sonnyp** [comment]
@smokku can you elaborate?

**Comment by smokku** [comment]
Running `xmpp-console "xmpp:user@localhost" "password"` ends with:
```xml
⮊ OUT
<iq type="set" id="9954011249717829">
  <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/>
</iq>
```
but to actually get online I need to manually send:
```xml
⮊ OUT
<iq type="set" id="123">
  <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/>
</iq>
```
This will request session creation and will give me `'online'` event.

**Comment by sonnyp** [comment]
@smokku `<session xmlns="urn:ietf:params:xml:ns:xmpp-session"/>` has been removed from the spec, please refer to https://xmpp.org/rfcs/rfc6120.html rather than https://xmpp.org/rfcs/rfc3920.html

**Comment by smokku** [comment]
So it is by design.

Should I create a bug, that node-xmpp-server still relies on it to bring user session online?
See: https://github.com/node-xmpp/node-xmpp/blob/master/packages/node-xmpp-server/lib/C2S/Session.js#L159 and https://github.com/node-xmpp/node-xmpp/blob/master/packages/node-xmpp-server/lib/C2S/Session.js#L335

**Comment by sonnyp** [comment]
@smokku yes please

**Comment by sonnyp** [comment]
@smokku thanks for the suggestions

> continuation prompt - as soon as I press Enter stanza is parsed and if it is not complete I get ❌ invalid XML "<..." Error: Incomplete document; and as transmitted stanzas are pretty-printed it is painful to copy-paste stanzas from previous session to send again (see previous point)

What solution do you suggest?

**Comment by smokku** [comment]
_continuation prompt_ - similar to what you have in shell if you type: cat "<ENTER>

**Comment by sonnyp** [comment]
@smokku can you open an issue for continuation prompt?

**Comment by smokku** [comment]
Does it make sense, when the preferred (at least for me now) way of running console is via `rlwrap`?
