### ISSUE TITLE
Allow to pass 'options' object to websocket connection

### ISSUE THREAD

**Issue by oanguenot** [node-xmpp/node-xmpp#378]
Hi,

there is no way today to pass websocket 'options' parameter (e.g. proxy agent) ?

Is it possible to modify the line:

this.websocket = new WebSocket(this.url, ['xmpp'])

by

this.websocket = new WebSocket(this.url, ['xmpp'], opts.websocket.options)

Thanks in advance,
Olivier

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp/pull/325

**Comment by oanguenot** [comment]
Thanks for your quick answer,
I don't find it in the node-xmpp-client 3.1.3. 
Is there an other release containing this fix that I can install from npm ?

Thanks,
Olivier

**Comment by sonnyp** [comment]
`3.2.0` sorry for the delay

**Comment by oanguenot** [comment]
No problem.

Thanks you,
Olivier

2017-03-03 20:45 GMT+01:00 Sonny Piers <notifications@github.com>:

**Comment by zucher** [comment]
Hi @sonnyp , with the last xmpp.js version 0.2.0 the same kind of feature missing, could you transpose your web socket options fix into this new version please?
