### ISSUE TITLE
xmpp-jid fails to install optional dependency

### ISSUE THREAD

**Issue by mohd-akram** [node-xmpp/node-xmpp#387]
xmpp-jid is using an older version of node-stringprep which fails to install on Node v7.6.0.

**Comment by sonnyp** [comment]
`xmpp-jid` is not part of `node-xmpp` see https://github.com/otalk/xmpp-jid

Ours is `@xmpp/jid` https://github.com/node-xmpp/node-xmpp/tree/master/packages/jid

**Comment by mohd-akram** [comment]
D'oh, sorry about that.
