### ISSUE TITLE
How to keep alive

### ISSUE THREAD

**Issue by XiaoHanChina** [node-xmpp/node-xmpp#389]
Summary:
         client send message to app, ok; 
         client send ping xml to ejabberd server, ok, and client can also receive the stanza sent by server when client ping.
         When app send message to client, cliend receive nothing, and the client is offline on the app(iOS: AstraChat, BoogieChat)

Detail:
I'm using the 'node-xmpp-client' to make a demo, and I can send one message to the other users registered in my ejabberd server. But I don't know how to make this client keep alive.

this is my demo

index.html

```
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <script src="node-xmpp.js"></script>
    <!--<script src="../../index.js"></script>-->
    <script src="chat.js"></script>
  </head>
  <body>
  </body>
</html>
```
chat.js
```
(function (global) {
  'use strict'

  var XMPP = global.XMPP

  /* Note these are connection details for a local dev server :) */
  var client = new XMPP.Client({
    websocket: { url: 'ws://1.1.1.1:5280/websocket/' },
    jid: 'xx@domin.com',
    password: '123456',
    host:'1.1.1.1',
    preferred: 'PLAIN',
    reconnect: true
  })

  client.on('online', function () {
    console.log('online')

    var recipients = ['zz@domin.com']
    recipients.forEach(function (to) {
      var stanza = new XMPP.Element('message', {to: to, type: 'chat'})
        .c('body')
        .t('Hello from browser')
      client.send(stanza)
    })
    

  })

  client.on('stanza', function(stanza) {
    console.log('Incoming stanza: ')
    // console.log('Incoming stanza: ', stanza.toString())
  })

  client.on('error', function (err) {
    console.error(err)
  })
  
}(this))
```
the 'node-xmpp.js' is build by [https://github.com/node-xmpp/node-xmpp/tree/master/packages/node-xmpp-client](url)

**Comment by XiaoHanChina** [comment]
And I have no idea where to use the code below.
`this.client.connection.socket.setTimeout(0)
this.client.connection.socket.setKeepAlive(true, 10000)`

this is my first time to use this, sorry for my bad code format and my poor english.

**Comment by XiaoHanChina** [comment]
when i use setInterval to send message, it's ok. But on my other xmpp app, it seem's like the user uses this js is offline. and can't receive messages.
```
  setInterval(function () {
      // can always send message 
      recipients.forEach(function (to) { var stanza = new
      XMPP.Element('message', {to: to, type: 'chat'})   .c('body')   .t('ping')
      client.send(stanza) })
    }, 1000)
```

**Comment by sonnyp** [comment]
My best guess is that you don't reply to pings sent by ejabberd.

**Comment by XiaoHanChina** [comment]
the main issues is that when i login my accout(xx@domain.com) by the code above, the user(zz@domain.com) logon by iOS APP send message to  xx, and xx is offline in zz's user list

**Comment by sonnyp** [comment]
You need to send a presence stanza once connected.

**Comment by XiaoHanChina** [comment]
OK， i will try to do that tomorrow， cuz it is midnight now in China.  see you.

**Comment by XiaoHanChina** [comment]
Wonderful! It works now! Thanks for your help.
 And one more questions, where could I find detail docs, something like the XMPP.Element has the function c/t/up, and the client.on can listen the status 'online'/'error'/'offline', etc.
```
client.send(new XMPP.Element('presence', {})
      .c('show').t('chat').up()
      .c('status').t('hello everyone')
    )
```
```
client.on('stanza', function (stanza) {
    if (stanza.is('message') && (stanza.attrs.type == 'chat')) {
      // chat from other users
      console.log('Incoming stanza: ', stanza.getChildText('body'))
    } else {
      // others
      console.log('Incoming stanza: ', stanza.toString())
    }
```

**Comment by sonnyp** [comment]
We're lacking in documentation for the moment. You're best bet is the examples and the source code.
