### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by IegorKozakov** [node-xmpp/node-xmpp#395]
Hello. As I see, there was a lot of changes in your repository, but you still don't merge them. 

Can you tell me, are you still in progress, or you stop working on this lib? 
 
I'm waiting for a new version of the node-xmpp-client.

**Comment by sonnyp** [comment]
Hello,

Most changes are for `@xmpp/*` packages which are in pre release stage at this moment. node-xmpp-client didn't change. Are you waiting for something in particular?

**Comment by IegorKozakov** [comment]
Hello. I just want to be sure, that you will not release the major version of the client.
Also, want to know, will add stream management in your lib?

https://xmpp.org/extensions/xep-0198.html

Here is workaround of this XEP
https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/src/plugins/streamManagement.js

**Comment by sonnyp** [comment]
`node-xmpp-client` shouldn't receive any breaking updates but `@xmpp/client` should be released before the summer and is not API compatible with `node-xmpp-client` altough switching should be fairly easy. Stream management should be implemented by then.

**Comment by IegorKozakov** [comment]
Thanks a lot for your time.
Best wishes.

**Comment by jsrhome** [comment]
Is there support for client stream management (XEP-0198) in the current version (0.3.0)?  If not, do you have advice on adding this capability?

Thanks.
