### ISSUE TITLE
Delivering XMPP message to a Client which is offline 

### ISSUE THREAD

**Issue by siptowebrtc** [node-xmpp/node-xmpp#399]
We are using node-xmpp  with Cisco IM&P  and its working fine except its not able to deliver a message to Jabber client which is offline.

However Jabber  to Jabber offline message  works fine , which makes us believe  that server has the capability to deliver offline messages 

Can anyone suggest  is there are specific message format to be followed to send these XMPP message
when the other party is offline.

**Comment by sonnyp** [comment]
Offline message delivery is the responsibility of the server.

Are you using node-xmpp on the sender or recipient end?

In the first case there's no much you can do client side, on the recipient end make sure you sent a `<presence/>` stanza after connecting.
