### ISSUE TITLE
line breaks and white space in SASL data are not standard compliant

### ISSUE THREAD

**Issue by smokku** [node-xmpp/node-xmpp#403]
https://github.com/node-xmpp/node-xmpp/blob/master/packages/plugins/sasl/lib/SASLPlugin.js#L111
sends:
```xml
<auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">
  AHRlc3QAdGVzdA==
</auth>
```
Where https://tools.ietf.org/html/rfc4648#section-3.3 states:
```txt
   Implementations MUST reject the encoded data if it contains
   characters outside the base alphabet when interpreting base-encoded
   data, unless the specification referring to this document explicitly
   states otherwise.
```
and https://tools.ietf.org/html/rfc6595#section-5.1
```txt
Step 4: [...]
    <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='SAML20'>
    biwsZXhhbXBsZS5vcmc=</auth>
[...]
Please note: Line breaks were added to the base64 data for clarity.
```

Thus, standard-compliant XMPP server MUST reject `<auth>` stanza generated by node-xmpp.

(And i.e. jabberd2 using LibGSASL does so.)

**Comment by smokku** [comment]
`<response>` in https://github.com/node-xmpp/node-xmpp/blob/master/packages/plugins/sasl/lib/SASLPlugin.js#L89 should also have whitespace removed.

**Comment by sonnyp** [comment]
@smokku nice catch.

Should be an easy fix, would you like to take care of it?

Additionally, I wonder if `xml` shouldn't strip line breaks between elements. What do you think?

**Comment by sonnyp** [comment]
I mean so that

```
xml`
<hello>
  <foo>
    test bar
  </foo>
</hello>
`.toString()
```

returns 
```
<hello><foo>test bar</foo></hello>
```

which implies we'd check indentation and trim it as well

**Comment by smokku** [comment]
I believe we should keep all white characters (space, tab, newline, carriage-return) as entered - these are significant in XML.

But to keep it easy on the developer, we should pass tagged strings through https://www.npmjs.com/package/dedent-js to allow indented code.

**Comment by sonnyp** [comment]
> I believe we should keep all white characters (space, tab, newline, carriage-return) as entered - these are significant in XML.

Agree.

> But to keep it easy on the developer, we should pass tagged strings through https://www.npmjs.com/package/dedent-js to allow indented code.

Yes, that's what I meant.

**Comment by sonnyp** [comment]
@smokku although trimming all children would be faster/simpler and cover most use cases. When the user needs to inserts line breaks and other whitespace characters between elements the pragmatic API can be used.

And we could ignore interpolation strings so that

```
const bar = `  hello  `

xml`
<foo>
  ${bar}
</foo>`.toString()
```
returns `<foo>  hello  </foo>`

**Comment by sonnyp** [comment]
Relevant:

https://github.com/andreypopp/es6-template-strings-jsx#es6-jsx-tagged-template-strings-to-js-transform
https://github.com/substack/hyperx/issues/6

**Comment by smokku** [comment]
Even simpler would be:
```js
xml`
<foo>
  {"   hello   "}
</foo>`
```
I think I'm fine with stripping whitespace, as long as we go all the way - either leave all or strip all. :)

**Comment by sonnyp** [comment]
@smokku thanks for the feedback

https://github.com/node-xmpp/node-xmpp/pull/405

`xml``` will now strips whitespaces except for substitutions.
