### ISSUE TITLE
WebSocket connection does not stop()

### ISSUE THREAD

**Issue by smokku** [node-xmpp/node-xmpp#407]
`Connection.stop()` method `close()`s the stream and then chains to `Connection.end()` promise, which resolves `.once()` `this.parser` `'end'` event gets emitted.

In case of normal TCP connection I believe it gets emitted from https://github.com/node-xmpp/node-xmpp/blob/master/packages/streamparser/index.js#L61 after receiving `</stream:stream>`.

But in case of WebSocket the ending packet is `<close xmlns='urn:ietf:params:xml:ns:xmpp-framing' />`.

**Comment by smokku** [comment]
I would like to fix this issue with a PR, but I'm not sure how. I don't want to couple StreamParser to WebSocket binding like it is now coupled to TCP binding.

**Comment by smokku** [comment]
I just realized that calling `Connection.end()` method does not make sens anyway in case of WebSocket. It tries to call `this.socket.end()`, which is not supported by WebSocket `Socket` implementation.

So I override `ConnectionWebSocket.end()` with:
```js
  end () {
    return new Promise((resolve, reject) => {
      this.once('close', resolve)
      this.socket.once('close', () => {
        this.emit('close')
      })
      this.socket.close()
    })
  }```

But it didn't work. `Connection.end()` is still being called instead `ConnectionWebSocket.end()`. Any ide why?

**Comment by sonnyp** [comment]
My bad.

https://github.com/node-xmpp/node-xmpp/blob/master/packages/plugins/websocket/lib/Socket.js#L36

Should be named `end`, not `close`. We implement the same API for each transports (basically the Node.js socket API). Do you want to make the PR or should I? In both case I'll add a test case.

**Comment by sonnyp** [comment]
I just realized even then it won't work as intended for TCP/TLS connections, I'm gonna send a PR.

**Comment by smokku** [comment]
Yup. Fixing websocket `Socket.js` to support `end()` will fix the crash in `handler`, but the main issue is that handler is called after `'end'` of parser. And Parser is not ended on websocket connection.

**Comment by sonnyp** [comment]
@smokku right, also the reconnect plugin is probably gonna be interferem you might want to disable it meanwhile

**Comment by sonnyp** [comment]
work in progress https://github.com/node-xmpp/node-xmpp/pull/414

**Comment by sonnyp** [comment]
Should be fixed on `master` @smokku please test and close :)

**Comment by sonnyp** [comment]
(reconnect and console are broken due to API changes, on it)

**Comment by smokku** [comment]
Tested and master fixes my problem.
