### ISSUE TITLE
duplicate plugin.js

### ISSUE THREAD

**Issue by ggozad** [node-xmpp/node-xmpp#409]
Hey :)
While rebasing my fork I stumbled upon packages/plugin/lib/Plugin.js which is duplicated with lower-case plugin.js
Can we fix this it seems to wreak havoc on my git.

**Comment by sonnyp** [comment]
I was just working on this :)

https://github.com/node-xmpp/node-xmpp/commit/4da354bee3a01d02d3aab2c7424e5e7a5c70d2fd#commitcomment-22311391

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp/pull/410
