### ISSUE TITLE
Connection.id() issues

### ISSUE THREAD

**Issue by smokku** [node-xmpp/node-xmpp#415]
Current `Connection.id()`:
```js
 id () {
  return Math.random().toString().split('0.')[1]
 }
```

1. A neat trick that gives strings of grater variety than plain number is
```js
Math.random().toString(36)
```

2. In case `Math.random()` returns `0` this function returns `undefined`
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random
> The Math.random() function returns a floating-point, pseudo-random number in the range [0, 1); that is, from 0 (inclusive) up to but not including 1 (exclusive)

3. This really is not method and does not belong to `Connection` class. It works solely on externally provided data.
http://wiki.c2.com/?FeatureEnvySmell

**Comment by smokku** [comment]
Here's a function I came up in my codebase:
`cat traffic/utils.js`
```js
'use strict'

exports.uniq = function (len = 7) {
  var ret = ''
  while (ret.length < len) {
    ret += Math.random().toString(36).substr(2) // start at 2 character to skip "0."
  }
  return ret.substr(0, len)
}
```

If it is OK, I could do PR. :-)

**Comment by sonnyp** [comment]
@smokku you're absolutely right.

IIRC the connection `id` method is not even used although the `id` method of the `iq-caller` plugin is.

In the future, don't hesitate to send PR directly without opening issues.
