### ISSUE TITLE
Issue while installing node-xmpp-core

### ISSUE THREAD

**Issue by kumar163** [node-xmpp/node-xmpp#420]
I'm getting below error while installing this module.

Versions : 
Node - 4.4.3
NPM - 3.8.9
Linux - RHEL 6.8
GCC : 4.8.2

> 
> > node-stringprep@0.8.0 install /opt/sit/.../server/node_modules/node-stringprep
> > node-gyp rebuild
> 
> make: Entering directory `/opt/sit/.../server/node_modules/node-stringprep/build'
>   CXX(target) Release/obj.target/node_stringprep/node-stringprep.o
> ../node-stringprep.cc: In function âNan::NAN_METHOD_RETURN_TYPE ToUnicode(Nan::NAN_METHOD_ARGS_TYPE)â:
> ../node-stringprep.cc:199:5: error: âUIDNAâ was not declared in this scope
>      UIDNA *uidna = uidna_openUTS46(options, &error);
>      ^
> ../node-stringprep.cc:199:12: error: âuidnaâ was not declared in this scope
>      UIDNA *uidna = uidna_openUTS46(options, &error);
>             ^
> ../node-stringprep.cc:199:51: error: âuidna_openUTS46â was not declared in this scope
>      UIDNA *uidna = uidna_openUTS46(options, &error);
>                                                    ^
> ../node-stringprep.cc:212:9: error: âUIDNAInfoâ was not declared in this scope
>          UIDNAInfo uinfo = UIDNA_INFO_INITIALIZER;
>          ^
> ../node-stringprep.cc:212:19: error: expected â;â before âuinfoâ
>          UIDNAInfo uinfo = UIDNA_INFO_INITIALIZER;
>                    ^
> ../node-stringprep.cc:217:12: error: âuinfoâ was not declared in this scope
>            &uinfo, &error);
>             ^
> ../node-stringprep.cc:217:25: error: âuidna_nameToUnicodeâ was not declared in this scope
>            &uinfo, &error);
>                          ^
> ../node-stringprep.cc:230:30: error: âuidna_closeâ was not declared in this scope
>              uidna_close(uidna);
>                               ^
> ../node-stringprep.cc:240:22: error: âuidna_closeâ was not declared in this scope
>      uidna_close(uidna);
>                       ^
> ../node-stringprep.cc: In function âNan::NAN_METHOD_RETURN_TYPE ToASCII(Nan::NAN_METHOD_ARGS_TYPE)â:
> ../node-stringprep.cc:257:5: error: âUIDNAâ was not declared in this scope
>      UIDNA *uidna = uidna_openUTS46(options, &error);
>      ^
> ../node-stringprep.cc:257:12: error: âuidnaâ was not declared in this scope
>      UIDNA *uidna = uidna_openUTS46(options, &error);
>             ^
> ../node-stringprep.cc:257:51: error: âuidna_openUTS46â was not declared in this scope
>      UIDNA *uidna = uidna_openUTS46(options, &error);
>                                                    ^
> ../node-stringprep.cc:266:5: error: âUIDNAInfoâ was not declared in this scope
>      UIDNAInfo uinfo1 = UIDNA_INFO_INITIALIZER;
>      ^
> ../node-stringprep.cc:266:15: error: expected â;â before âuinfo1â
>      UIDNAInfo uinfo1 = UIDNA_INFO_INITIALIZER;
>                ^
> ../node-stringprep.cc:271:8: error: âuinfo1â was not declared in this scope
>        &uinfo1, &error);
>         ^
> ../node-stringprep.cc:271:22: error: âuidna_nameToASCIIâ was not declared in this scope
>        &uinfo1, &error);
>                       ^
> ../node-stringprep.cc:278:19: error: expected â;â before âuinfo2â
>          UIDNAInfo uinfo2 = UIDNA_INFO_INITIALIZER;
>                    ^
> ../node-stringprep.cc:283:12: error: âuinfo2â was not declared in this scope
>            &uinfo2, &error);
>             ^
> ../node-stringprep.cc:293:26: error: âuidna_closeâ was not declared in this scope
>          uidna_close(uidna);
>                           ^
> ../node-stringprep.cc:300:22: error: âuidna_closeâ was not declared in this scope
>      uidna_close(uidna);
>                       ^
> make: *** [Release/obj.target/node_stringprep/node-stringprep.o] Error 1
> make: Leaving directory `/opt/sit/.../server/node_modules/node-stringprep/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/opt/sit/.../node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Linux 2.6.32-642.3.1.el6.x86_64
> gyp ERR! command "/opt/sit/.../node/bin/node" "/opt/sit/.../node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /opt/sit/.../server/node_modules/node-stringprep
> gyp ERR! node -v v4.4.3
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> install â rollbackFailedO â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
> npm ERR! Linux 2.6.32-642.3.1.el6.x86_64
> npm ERR! argv "/opt/sit/.../node/bin/node" "/opt/sit/.../node/bin/npm" "i" "node-stringprep"
> npm ERR! node v4.4.3
> npm ERR! npm  v3.8.9
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-stringprep@0.8.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
>

**Comment by sonnyp** [comment]
node-xmpp-core doesn't uses node-stringprep anymore, use a recent a version
