### ISSUE TITLE
Calling client.start() many times leaks websocket connections

### ISSUE THREAD

**Issue by smokku** [node-xmpp/node-xmpp#423]
plugins/websocket/lib/Socket.js
```js
const sock = this.socket = new WebSocket(url, ['xmpp'])
```
will overwrite and leak WebSocket connection when calling start on an already started client connection.

**Comment by sonnyp** [comment]
I propose start resolves if the entity is already online.

**Comment by smokku** [comment]
+1

**Comment by sonnyp** [comment]
and stop resolves if entity is already offline/stopping/closing/...

**Comment by sonnyp** [comment]
@smokku or we could cache the initial start/stop promise and return that

What do you think?

**Comment by sonnyp** [comment]
hmm actually I'm thinking throwing would probably better, there's no reason to call start twice

**Comment by smokku** [comment]
How would .catch() determine whether the connection actually failed or it is fine but already connected? 




smk







On Tue, Jun 6, 2017 at 3:28 PM +0200, "Sonny Piers" <notifications@github.com> wrote:












hmm actually I'm thinking throwing would probably better, there's no reason to call start twice

**Comment by smokku** [comment]
Thinking of it... Resolving is not correct, as we cannot guarantee that the client is connected to the server user intended. And even if we compare the URLs, then we cannot guarantee that the JID/resource is the intended one.

If the application is willing to work with already started connection, it is up to the application code to decide how to handle it.

**Comment by sonnyp** [comment]
@smokku agree plus the reconnect plugin is supposed to handle everything for the user so there's definitely no reasons to call start twice.

What about `stop()` ? On one hand I feel like it should be consistent with `start` on the other, you might wanna call stop any time even if you're not already connect without throwing.

Thoughts?

**Comment by smokku** [comment]
I think `.stop()` should be safe escape hatch. No matter the connection state it should just shut it down. It should be safe to call `.stop()` in every error handler, catch, etc. Just call `stop()` to be safe and try to recover.

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp/pull/428
