### ISSUE TITLE
SASL authentication error handling

### ISSUE THREAD

**Issue by ggozad** [node-xmpp/node-xmpp#426]
If the SASL connection fails an element `<failure/>` is returned. It is assumed in the code that it will contain a `<text/>` child which is parsed and passed to the rejection.
Not sure if there is a `<text/>` child in prosody but definitely not on ejabberd and not in the spec iirc.

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp/pull/427
