### ISSUE TITLE
proposal for better interface to writing xml

### ISSUE THREAD

**Issue by sonnyp** [node-xmpp/node-xmpp#435]
cc @ggozad @smokku @astro @lloydwatkin 

# proposal 

I'd like to remove the jsx and tagged template interfaces and introduce the following for 1.0:

```js
const x = require('@xmpp/xml')
const to = 'user@example.com'
const days = ['Monday', 'Tuesday']

const message = (
  x('message', {to},
    x('body', {}, 1 + 2),
    x('days',
      days.map(day => x('day', {}, day))
    )
  )
)
```

```xml
<message to="user@example.com">
  <body>3</body>
  <days>
    <day>Monday</day>
    <day>Tuesday</day>
  </days>
</message>
```

Inspired by [hyperscript](https://github.com/hyperhype/hyperscript).

tagged template and jsx interfaces would still be available to users via the `ltx` package but xmpp.js would forbid their usage for code and plugins contributions.

# Why

The tagged template interface is the slowest and while it shouldn't be an issue for most clients it'll be on the server specially when when we'll share plugins. Its handling of whitespaces is not straightforward. There's no tooling available so we (and users) don't have linting or syntax highlight. As a bonus, removing it will help get under 10Kb for the browser bundle.

The JSX interface requires a preprocessor and doesn't allow for namespace attributes.

I don't like offering multiple interfaces at it might confuse users.

While working on the documentation I came to realize most users shouldn't have to write a single line of XML thanks to the plugins so having a familiar HTML/XML syntax isn't as important as I initially though.

We need to get this right for 1.0.

----

What do you think?

If there's no case against the proposal I'll port the code over to this new API.

**Comment by sonnyp** [comment]
I forgot the cons of the new interface:

Makes writing one line xml a bit weird

```js
x('message', x('body', 'hello'))
```
but we never do that anyway and enforce line breaks

Doesn't allow to capy paste XML from an external source (XEP, RFCs, ...) into the code but we could write a simple converter.

Still I think this is the right interface for node-xmpp/xmpp.js

**Comment by sonnyp** [comment]
An other pro in favor of this new interface, 

```js
const id = 'foobar'
xml('message', {id})
```

**Comment by smokku** [comment]
Doesn't pragma:

    /** @jsx x */

produce the exact hyperscript-like calls when transforming JSX?

**Comment by smokku** [comment]
I'm afraid discouraging tagged template might hurt xmpp.js popularity.
It won't be so appealing to newcomers anymore.

 While I believe the hyperscript is great and like your proposal very much, I personally would still prefer writing XMPP stanzas that look like XML blocks in my code. It does not require the mental effort to transform hyperscript to XML in head each time I compare the code with the output (i.e. watching logs).

I really like the JSX approach, where you still write XML-like code, but underneath it gets transformed to hyperscript. What exact problems are with JSX approach? Maybe we could work around these?

**Comment by smokku** [comment]
Anyway, I am for changing the internal code of the library to use the hyperscript interface (for performance reasons and to not require preprocessing), but we should keep tagged/JSX in all user-facing documentation, examples, README etc. We can then mention using direct hyperscript interface in advanced topics / performance optimisation / plugin writing documentation.

**Comment by ggozad** [comment]
Have to admit I came to like using jsx for writing plugins because it requires no effort to mentally parse afterwards. I can practically copy/paste stanzas and all works :)
Some counter-arguments:
Speed should not be an issue and I suspect the server story is not the strong point here given there is pretty good competition.
Users will have to still write xml, unless we make some very complex API for plugins. Consider pubsub for example where an ``<entry/>`` is really arbitrary, can be atom, text or some custom cruft.
jsx is really a standard now due to react and friends.

That said I do not have strong opinions on this and can rewrite plugins.

**Comment by sonnyp** [comment]
@ggozad 

> Have to admit I came to like using jsx for writing plugins because it requires no effort to mentally parse afterwards. I can practically copy/paste stanzas and all works :)

Do you mean the tagged template interface rather than jsx?

> Users will have to still write xml, unless we make some very complex API for plugins. Consider pubsub for example where an <entry/> is really arbitrary, can be atom, text or some custom cruft.

true

@smokku 

> I really like the JSX approach, where you still write XML-like code, but underneath it gets transformed to hyperscript. What exact problems are with JSX approach? Maybe we could work around these?

JSX doesn't support namespace. 

`<data foo:bar="test"/>`

`<foo:data/>`

---

Okay so as I understand the conclusion is that the hyperscript + the jsx interfaces is the perfect solution. I kinda agree specially since it's supported out of the box with the proposal interface. But to do it right we should fork the babel jsx plugin to allow for namespace attributes and names, not sure I'll have the time before 1.0

**Comment by smokku** [comment]
What if we replace `:` with a symbol-legal character (but illegal in XML name)?

[Babel REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=PQKgBAAgVgzgHmBJgCgA8AzA9lsA7AQwFsBTAXgHIAjAgLwsSIBs8YASbLSgnigPhRgwaHgTY0ATmCoyyAIgDGSuWGAC0wTnyA)
```jsx
/* @jsx x */
<foo name='baz' xmlns$foo='aaa'>
  <aaa$bar bbb="ccc" />
</foo>
```
Doesn't really look bad, and could keep us afloat until we could upstream support for `:` in Babel.

**Comment by sonnyp** [comment]
> Doesn't really look bad, and could keep us afloat until we could upstream support for : in Babel.

I don't think Babel will be interested in our use case. I think an xml babel plugin forked from jsx plugin is fine and doesn't have to be merged upstream.

**Comment by sonnyp** [comment]
Oh and also IIRC jsx doesn't allow for this

```
const foo = <{'name'}/>
```

**Comment by sonnyp** [comment]
Let's use jsx in the tests when possible, we have tons of xml there and we already have babel thanks to ava.

**Comment by sonnyp** [comment]
until we fork babbel-plugin-transform-react-jsx here is a workaround for namespaces 

https://github.com/node-xmpp/node-xmpp/pull/436/files#diff-5958a2752227b744326a80a0863e09b3R22
