### ISSUE TITLE
Node require problems

### ISSUE THREAD

**Issue by jonator** [node-xmpp/node-xmpp#437]
```
webpack built 6e3e56702d892b1a769e in 1565ms
Version: webpack 1.15.0
Time: 1565ms
            Asset     Size  Chunks       Chunk Names
static/js/main.js  2.22 MB       0       main

ERROR in ./~/node-xmpp-client/lib/Client.js
Module not found: Error: Cannot resolve module 'child_process' in C:\Dev\clinical.messaging\node_modules\node-xmpp-client\lib
 @ ./~/node-xmpp-client/lib/Client.js 15:11-35

ERROR in ./~/node-xmpp-client/lib/session.js
Module not found: Error: Cannot resolve module 'tls' in C:\Dev\clinical.messaging\node_modules\node-xmpp-client\lib
 @ ./~/node-xmpp-client/lib/session.js 3:10-24

ERROR in ./~/node-xmpp-core/lib/Connection.js
Module not found: Error: Cannot resolve module 'net' in C:\Dev\clinical.messaging\node_modules\node-xmpp-core\lib
 @ ./~/node-xmpp-core/lib/Connection.js 3:10-24

ERROR in ./~/node-xmpp-core/lib/SRV.js
Module not found: Error: Cannot resolve module 'dns' in C:\Dev\clinical.messaging\node_modules\node-xmpp-core\lib
 @ ./~/node-xmpp-core/lib/SRV.js 3:10-24
webpack: Failed to compile.
```

To install through npm all I used was 
`npm install node-xmpp`

**Comment by sonnyp** [comment]
try node-xmpp-client

**Comment by jonator** [comment]
The above error is shown in cmd when I use `npm start`. I did try using `npm install node-xmpp-client' and I get the `Cannot GET /` error. I'm just confused on how to implement node-xmpp into my node.js project.

**Comment by jonator** [comment]
It appears that some of the dependencies are not included maybe?

**Comment by sonnyp** [comment]
@jonator plugins are for the rewrite which is not released yet.

I don't understand what you're trying to do, why do you use webpack or npm start?

**Comment by jonator** [comment]
I have a project with an elm front-end and node/express back-end. I need a good library for using xmpp to communicate with ports to the front-end

And I don't know why we're using webpack, I forked this project as a template to work with elm

**Comment by jonator** [comment]
My pasted console result above is from using `npm start`. It's giving errors from the node-xmpp-core module, stating that there are unresolved sub-modules. By trying to `require('node-xmpp-client')` I get the `Cannot GET /` on my webpage, sorry for the horrible wording above.

**Comment by sonnyp** [comment]
Are you trying to use node-xmpp-client client or server side?

**Comment by jonator** [comment]
client side right now

**Comment by sonnyp** [comment]
@jonator I've never really used webpack so I don't know how it works but with some googling I found this https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285598881

An other solution is to use the browser bundle.

```xml
<script src="node_modules/node-xmpp-client/browserify.js"></script>
```
```js
window.XMPP
```

In any case if your project can wait a little bit, we're gonna release the rewrite soon (before Jully 1) and it should be much easier to use with webpack.

**Comment by jonator** [comment]
Ok, thanks for the support it is appreciated!

**Comment by pmbuban** [comment]
This is a really old issue but here's a solution that worked for my project. Add this to your webpack config

```
node: {
    net: 'empty',
},
```
