### ISSUE TITLE
Document for starting server and error while npm test

### ISSUE THREAD

**Issue by jamajdsdcvs** [node-xmpp/node-xmpp#440]
Proper documentation is not present for starting the server...And after doing 1)npm install node-xmpp-server 2)npm install -g mocha standard no errors were present,but after theses two steps if i do npm test i am getting error as shown in picture.
![untitled](https://user-images.githubusercontent.com/29754985/27640458-08a2db8e-5c37-11e7-8400-fd8814698554.png)

**Comment by sonnyp** [comment]
npm install first

then node-xmpp-server are libraries not an XMPP server ready to use

**Comment by sonnyp** [comment]
npm install first

then node-xmpp-server are libraries not an XMPP server ready to use
