### ISSUE TITLE
Proper Documentation is not there.

### ISSUE THREAD

**Issue by jamajdsdcvs** [node-xmpp/node-xmpp#441]
Need proper documentation about how to start the server and other things are not present.It would be helpful if it had a proper documentation,as above mentioned steps are not working...Getting an error as shown in picture
![error](https://user-images.githubusercontent.com/29754985/27680980-431c2bae-5cdb-11e7-9e34-e399656d4f5a.png)
![error2](https://user-images.githubusercontent.com/29754985/27680981-431cb3ee-5cdb-11e7-94f0-3d0503fb4f96.png)
![error3](https://user-images.githubusercontent.com/29754985/27680982-4330df7c-5cdb-11e7-85f0-2d54b87e45e0.png)

**Comment by sonnyp** [comment]
I already replied to you there https://github.com/node-xmpp/node-xmpp/issues/440

**Comment by jamajdsdcvs** [comment]
But its not working..Keep getting error as shown in picture

**Comment by sonnyp** [comment]
@jamajdsdcvs what are you trying to do?
